version: '2.1'

services:
  sylius:
    container_name: ${NAME}-app
    build:
        context: .
        args:
          - AS_UID=${AS_UID:-33}
    environment:
      - SYLIUS_DATABASE_HOST=mysql
      - SYLIUS_DATABASE_USER=sylius
      - SYLIUS_DATABASE_PASSWORD=sylius
      - SYLIUS_MAILER_HOST=mailhog:1025
      - SYLIUS_APP_DEV_PERMITTED=1
    ports:
      - 80:80
    volumes:
      - ./sylius:/var/www/sylius

  mysql:
    container_name: ${NAME}-mysql
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sylius
      MYSQL_DATABASE: sylius_dev
      MYSQL_USER: sylius
      MYSQL_PASSWORD: sylius
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

  node:
      image: node:carbon
      user: "node"
      working_dir: /var/www/symfony
      volumes_from:
          - sylius 
      ports:
          - 8081:8081
      tty: true

  mailhog:
    container_name: ${NAME}-mailhog
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
